const List<String> errorList = [
  'E1',
  'E2',
  'E3',
  'E4',
  'E5',
  '',
  'Water not Coming',
  'Water Inside Problem',
  'Water going continuously',
  'Not taking coin',
  'Took coin but not displayed',
  '',
  'Machine Not Working',
  'Door not opening',
  'Drum not rotating',
  'Vibration problem',
  'Not drying properly',
];
